@startuml
left header
	<font color=000 size=18><b>Package:</b> AD_1.4
	<font color=000 size=16><b>ID:</b> UC_3
	<font color=000 size=16><b>Назва:</b> Вхід у систему
	<font color=000 size=16><b>Учасники:</b> Користувач, Web-система
	<font color=000 size=16><b>Передумови:</b> Користувач знаходиться на Web-сторінці
	<font color=000 size=16><b>Результат:</b> Користувач входить у систему
	<font color=000 size=16><b>Виключні ситуації:</b>
	<font color=000 size=16> EX_3.1 Користувач натискає кнопку відміни;
	<font color=000 size=16> EX_3.2 Логін відсутній в базі даних;
	<font color=000 size=16> EX_3.3 Введено невірний пароль;
	<font color=000 size=16> EX_3.4 Користувач забув пароль;
	<font color=000 size=16><b>Основний сценарій:</b>
end header

|Користувач|
	start
	: Натискає кнопку входу в систему;
|Web-система|
	: Відображає форму входу;
	
	note right 
		Система запитує логін та пароль користувача
	end note
	
|Користувач|
	: Вводить логін та пароль;
	: Натискає кнопку підтвердження;
	
	note right #ffaaaa
		<b> Можливо
		<b> EX_3.1
	end note
	
|Web-система|
	:Підтверджує правильність заповненої форми;
	
	note right #ffaaaa
		<b> Можливо
		<b> EX_3.2
		<b> EX_3.3
		<b> EX_3.4
	end note

	: Дозволяє вхід;
|Користувач|
	stop;
@enduml
