@startuml
left header
	<font color=000 size=18><b>Package:</b> AD_1.3
	<font color=000 size=16><b>ID:</b> UC_2.2
	<font color=000 size=16><b>Назва:</b> Обробка API-запиту
	<font color=000 size=16><b>Учасники:</b> Користувач(СПЗ), Система
	<font color=000 size=16><b>Передумови:</b> Відсутні
	<font color=000 size=16><b>Результат:</b> Отримано відповідні дані
	<font color=000 size=16><b>Виключні ситуації:</b>
	<font color=000 size=16> EX_2.1 Введено невірний API-key
	<font color=000 size=16> EX_2.2 У базі даних немає відповідних даних
	<font color=000 size=16><b>Основний сценарій:</b>
end header

|Користувач|
	: Вводить довільне слово;
|Система|
	: Аназізує запит;
	
	note right #ffaaaa
		<b> Можливо
		<b> EX_2.1
	end note
	
	: Перевіряє наявність слова 
	у існуючій базі даних;
	
	note right #ffaaaa
		<b> Можливо
		<b> EX_2.2
	end note
	
	: Визначає теги частин мови
	відповідного слова;
	: За допомогою тегу система знаходить 
	відповідні правила відмінювання 
	у каталозі афіксів;
	: Генерує словоформи заданого слова;
	
	note right 
		Будуть згенеровані 
		лема (у випадку введення
		слова не у початковій формі)
		і всі можливі словоформи
		введеного слова
	end note
	
	: Повертає дані у форматі JSON;
|Користувач|
	: Отримує дані;
	stop;
@enduml
