@startuml
left header
	<font color=000 size=18><b>Package:</b> AD_1.5
	<font color=000 size=16><b>ID:</b> UC_4
	<font color=000 size=16><b>Назва:</b> Додавання нових слів
	<font color=000 size=16><b>Учасники:</b> Користувач, Web-система, Система
	<font color=000 size=16><b>Передумови:</b> Користувач увійшов в обліковий запис
	<font color=000 size=16><b>Результат:</b> Слово додано у базу даних
	<font color=000 size=16><b>Виключні ситуації:</b>
	<font color=000 size=16> EX_4.1 Згенеровані некоректні словоформи;
	<font color=000 size=16><b>Основний сценарій:</b>
end header

|Користувач|
	start
	: Вводить слово і відповідні теги;
|Web-система|
	: Аналізує запит;
	: Перенаправляє до системи;
|Система|
	: Аналізує запит;
	: За допомогою тегу система знаходить відповідні
	правила відмінювання у каталозі афіксів;
	: Система генерує усі можливі словоформи заданого слова;

	note right #ffaaaa
		<b> Можливо
		<b> EX_4.1
	end note

	: Повертає дані у форматі JSON;
|Web-система|
	: Відображає відповідні дані;
|Користувач|
	: Натискає кнопку підтвердження;
|Web-система|
	:Аналізує проведені дії;
	: Перенаправляє до системи;
|Система|
	: додає відповідне слово до бази даних;
	stop;
@enduml
