@startuml
right header
	<font size=24 color=black>Package: <b>BEM_1.1
end header
 
title
	<font size=18 color=black> Веб-проект "Електронний словник української мови"
	<font size=16 color=black>BE-модель 
end title

entity MainForm
entity MainForm.value


entity Word 
entity Word.value


entity Tag
entity Tag.name
entity Tag.description


entity Association 

MainForm.value -u-* MainForm

Word.value -u-* Word

Tag.name -u-* Tag
Tag.description -u-* Tag

Association "0,*" -u- "1,1" Word
Association "0,*" -u- "1,1" MainForm
Association "0,*" -u- "1,1" Tag



 
right footer
 
 НТУУ КПІ ім.І.Сікорського
 Киів-2020 
 end footer
@enduml