@startuml
right header
	<font size=24 color=black>Package: <b>BEM_1.0
end header
 
title
	<font size=18 color=black> Веб-проект "Електронний словник української мови"
	<font size=16 color=black>BE-модель 
end title
 
 entity User
 
 entity User.id
   
 entity UserAkk
 
 entity UserAkk.login
 entity UserAkk.password
 entity UserAkk.email
 
 entity APIkey
 entity APIkey.value

 entity Request

 entity Request.id
 entity Request.data
 
 entity Reply

 entity Reply.id
 entity Reply.data
 entity Reply.exeptions
 entity Reply.exeptions.data

 
 Request.id -u-* Request
 Request.data -u-* Request
 
 Reply.id -u-* Reply
 Reply.data -u-* Reply
 Reply.exeptions -u-* Reply
 Reply.exeptions.data -u-* Reply.exeptions
 
 User.id -* User
 
 UserAkk.login -u-* UserAkk
 UserAkk.password -u-* UserAkk
 UserAkk.email -u-* UserAkk
 
   
 APIkey.value -u-* APIkey
   
 APIkey "0,*" -- "1,1" UserAkk
 
 User "0,*"-u- "1,1" UserAkk
 Request "0,*"-- "1,1" User
 Reply "0,*" -- "1,1" User
 
right footer
 
 НТУУ КПІ ім.І.Сікорського
 Киів-2020 
 end footer
@enduml